name: Sync to HuggingFace Space

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git remote add hf https://Adityahars:$HF_TOKEN@huggingface.co/spaces/Adityahars/Sanskrit-env
          git push hf main --force
